// Example 6.2 TodoAngular/todo-angular-app/src/app/todo/todo-form/todo-form.component.ts
import { Component } from '@angular/core';
import { Todo } from 'src/app/shared/todo';
import { TodosService } from '../../shared/todos.service';

@Component({
  selector: 'app-todo-form',
  templateUrl: './todo-form.component.html',
  styleUrls: ['./todo-form.component.css'],
})
export class TodoFormComponent {
  title: string = '';

  constructor(private todoService: TodosService) {}

  submit() {
    if (!this.title) return;
    const todo: Todo = {
      id: 0,
      text: this.title,
      created: new Date(),
      done: false,
    };
    this.todoService.add(todo);
    this.title = '';
  }
}

<form class="d-flex gap-2 mb-3">
  <input
    type="text"
    class="form-control"
    name="text"
    placeholder="Введите текст задачи"
    [(ngModel)]="title"
    (keydown.enter)="submit()"
  />
  <button class="btn btn-primary" (click)="submit()">Добавить</button>
</form>

// Example 6.1 TodoReact/todo-react-app/src/components/Todo/TodoForm.tsx
import React, { useState } from "react";
import { Todo } from "../../data/Todo";

export interface TodoFormProps {
    handleSubmit: (todo: Todo) => void;
}

export const TodoForm: React.FC<TodoFormProps> = ({ handleSubmit }) => {
    const [text, setText] = useState("");
    return (
        <form
            id="todoList-form"
            className="d-flex gap-2 mb-3"
            onSubmit={(evt) => {
                evt.preventDefault();
                handleSubmit({ id: 0, text, created: new Date(), done: false });
                setText("");
            }}
        >
            <input
                type="text"
                className="form-control"
                name="text"
                placeholder="Введите текст задачи"
                value={text}
                onChange={(evt) => setText(evt.target.value)}
            />
            <button className="btn btn-primary" type="submit">
                Добавить
            </button>
        </form>
    );
};
