// Example 6.2 TodoAngular/todo-angular-app/src/app/todo/todo-list/todo-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CdkDragDrop } from '@angular/cdk/drag-drop';
import { Todo } from '../../shared/todo';
import { TodosService } from '../../shared/todos.service';

@Component({
  selector: 'app-todo-list',
  templateUrl: './todo-list.component.html',
  styleUrls: ['./todo-list.component.css'],
})
export class TodoListComponent implements OnInit {
  loading: boolean = true;

  public get todos() {
    return this.todosService.todos;
  }
  public maxIndex() {
    return this.todosService.todos.length - 1;
  }
  constructor(private todosService: TodosService) {}

  ngOnInit(): void {
    this.todosService.fetchTodos().subscribe(() => {
      this.loading = false;
    });
  }

  drop(event: CdkDragDrop<Todo[]>) {
    this.todosService.move(
      this.todosService.todos[event.previousIndex],
      event.currentIndex
    );
  }
}

<div>
  <div *ngIf="loading" class="d-flex justify-content-center align-items-center">
    <div
      class="spinner-border text-primary align-self-center"
      role="status"
      title="Загрузка..."
    >
      <span class="visually-hidden">Загрузка...</span>
    </div>
  </div>
  <div *ngIf="todos.length == 0"><em>Список задач пуст</em></div>
  <ol
    class="list-group todo-list"
    cdkDropList
    (cdkDropListDropped)="drop($event)"
  >
    <app-todo-list-item
      *ngFor="let todo of todos; let i = index"
      [todo]="todo"
      [index]="i"
      [maxIndex]="maxIndex()"
    ></app-todo-list-item>
  </ol>
</div>

// Example 6.1 TodoReact/todo-react-app/src/components/Todo/TodoList.tsx
import React, { useEffect, useState } from "react";

import { Todo } from "../../data/Todo";
import { TodoListItem } from "./TodoListItem";
import { TodoForm } from "./TodoForm";
import { todoApi } from "../../utils/api";

import "./Todo.css";

export const TodoList: React.FC = () => {
    const [todos, setTodos] = React.useState<Todo[]>([]);
    const [dragTargetIndex, setDragTargetIndex] = React.useState<number | null>(
        null
    );
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        if (loading) {
            todoApi
                .getAll()
                .then((todos) => {
                    setTodos(todos);
                })
                .finally(() => setLoading(false));
        }
    }, [loading]);

    function moveTodoListItem(todo: Todo, index?: number) {
        if (index === undefined) {
            if (dragTargetIndex !== null) {
                index = dragTargetIndex;
            } else {
                return;
            }
        }
        todoApi.moveto(todo, todos[index], true).then(() => {
            const newTodos = todos.filter(
                (td, i) => i === index || td.id !== todo.id
            );
            newTodos.splice(index || 0, 0, todo);
            setTodos(newTodos);
        });
    }

    function removeTodoListItem(todo: Todo) {
        todoApi.delete(todo).then(() => setLoading(true));
    }

    function addTodo(todo: Todo) {
        todoApi.post(todo).then(() => setLoading(true));
    }

    if (loading) {
        return (
            <div className="d-flex justify-content-center align-items-center">
                <div
                    className="spinner-border text-primary"
                    role="status"
                    title="Загрузка..."
                >
                    <span className="visually-hidden">Загрузка...</span>
                </div>
            </div>
        );
    }
    return (
        <>
            <TodoForm handleSubmit={(todo) => addTodo(todo)} />
            <div id="todoList-container">
                {todos.length > 0 ? (
                    <ol
                        id="todoList"
                        className="list-group list-group-numbered"
                    >
                        {todos.map((todo, i) => (
                            <TodoListItem
                                key={todo.id}
                                index={i}
                                maxIndex={todos.length - 1}
                                todo={todo}
                                moveTodoListItem={moveTodoListItem}
                                removeTodoListItem={removeTodoListItem}
                                setDragTarget={(todo, position) => {
                                    const index = todos.findIndex(
                                        (td) => td.id === todo.id
                                    );
                                    setDragTargetIndex(
                                        position === "before"
                                            ? index
                                            : index + 1
                                    );
                                }}
                            />
                        ))}
                    </ol>
                ) : (
                    <div>
                        <em>Список задач пуст</em>
                    </div>
                )}
            </div>
        </>
    );
};
